# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:alpine
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 5000:8080
    